---
name: "mindmapper3"
version: "0.1.0"

data:
  raw_txt_dir: "document_data/raw_txt"
  clean_txt_dir: "document_data/clean_txt"

supported_formats:
  - "pdf"
  - "txt"

random_seed: 42

pipeline:
  batch_size: 32
  max_workers: 4

logging:
  # Show INFO level messages and above --> Info, warning, error, critical, but NOT debug (bc too verbose)
  level: "INFO"
  # Format of log message - timestamp of when event happened, name of the logger (part of code logging it), log level, and message
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
